name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Build the Docker image
      run: |
        docker build ./app --tag marc1307/tailscale-cloudflare-dnssync:$(date +%s)
    
    - name: Docker Push
      run: |
        docker push marc1307/tailscale-cloudflare-dnssync
    
